# ZINIT
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"


# History
HISTORY_FILE="$HOME/.config/zsh/zsh_history"
if [[ ! -f "$HISTORY_FILE" ]]; then
        mkdir -p "$(dirname "$HISTORY_FILE")"
        touch "$HISTORY_FILE"
fi
HISTSIZE=5000
HISTFILE=$HISTORY_FILE
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# OH_MY_POSH
OH_MY_POSH_PATH="$HOME/.local/bin/oh-my-posh"
if [[ ! -f "$OH_MY_POSH_PATH" ]]; then
    curl -s https://ohmyposh.dev/install.sh | bash > /dev/null 2>&1
fi
export PATH=$PATH:$HOME/.local/bin
